import React, { useState, useEffect } from 'react';
<<<<<<< HEAD
import { fetchImages, uploadImage, deleteImage } from './api';

function App() {
  const [images, setImages] = useState([]);
  const [file, setFile] = useState(null);
  const [loading, setLoading] = useState(false);

  const loadImages = async () => {
    try {
      const res = await fetchImages();
      setImages(res.data);
    } catch (err) {
      console.error('Error loading images:', err);
    }
  };

  useEffect(() => {
    loadImages();
  }, []);

  const handleUpload = async (e) => {
    e.preventDefault();
    if (!file) return;
    const formData = new FormData();
    formData.append('image', file);
    setLoading(true);
    try {
      await uploadImage(formData);
      setFile(null);
      loadImages();
    } catch (err) {
      console.error('Error uploading image:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async (id) => {
    try {
      await deleteImage(id);
    } catch (err) {
      console.error('Error deleting image:', err);
    } finally {
      // Optimistically update local UI state regardless of server status
      setImages((prev) => prev.filter((img) => img._id !== id));
    }
  };

  return (
    <div style={{ padding: '20px', fontFamily: 'sans-serif' }}>
      <h1>Image Gallery</h1>
      <form onSubmit={handleUpload} style={{ marginBottom: '20px' }}>
        <input 
          type="file" 
          onChange={(e) => setFile(e.target.files[0])} 
          accept="image/*"
        />
        <button type="submit" disabled={loading}>
          {loading ? 'Uploading...' : 'Upload Image'}
        </button>
      </form>

      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '15px' }}>
        {images.map((img) => (
          <div key={img._id} style={{ border: '1px solid #ccc', padding: '10px', borderRadius: '5px' }}>
            <img 
              src={img.imageUrl} 
              alt="Uploaded" 
              style={{ width: '200px', height: '150px', objectFit: 'cover' }} 
            />
            <br />
            <button 
              onClick={() => handleDelete(img._id)} 
              style={{ marginTop: '10px', backgroundColor: '#ff4d4d', color: '#fff', border: 'none', padding: '5px 10px', cursor: 'pointer' }}
            >
              Delete
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}

export default App;
=======
import io from 'socket.io-client';
import axios from 'axios';
import './App.css';

const socket = io('http://localhost:5000', { withCredentials: true, autoConnect: false });

export default function App() {
  const [user, setUser] = useState(null);
    const [email, setEmail] = useState('');
      const [password, setPassword] = useState('');
        const [name, setName] = useState('');
          const [isRegister, setIsRegister] = useState(false);

            const [onlineCount, setOnlineCount] = useState(0);
              const [users, setUsers] = useState([]);
                const [selectedUser, setSelectedUser] = useState(null);
                  const [messages, setMessages] = useState([]);
                    const [text, setText] = useState('');
                      const [unreadMap, setUnreadMap] = useState({});

                        useEffect(() => {
                            if (user) {
                                  socket.connect();

                                        socket.on('online:count', (count) => setOnlineCount(count));
                                              socket.on('chat:history', (msgs) => setMessages(msgs));
                                                    
                                                          socket.on('chat:message', (msg) => {
                                                                  setMessages((prev) => [...prev, msg]);
                                                                        });

                                                                              socket.on('chat:unread', (unreadList) => {
                                                                                      const map = {};
                                                                                              unreadList.forEach(u => map[u.userId] = u.count);
                                                                                                      setUnreadMap(map);
                                                                                                            });

                                                                                                                  socket.on('chat:unread:update', ({ userId, count }) => {
                                                                                                                          setUnreadMap((prev) => ({ ...prev, [userId]: count }));
                                                                                                                                });

                                                                                                                                      socket.emit('chat:unread');

                                                                                                                                            return () => {
                                                                                                                                                    socket.disconnect();
                                                                                                                                                          };
                                                                                                                                                              }
                                                                                                                                                                }, [user]);

                                                                                                                                                                  const handleAuth = async (e) => {
                                                                                                                                                                      e.preventDefault();
                                                                                                                                                                          const endpoint = isRegister ? '/api/register' : '/api/login';
                                                                                                                                                                              try {
                                                                                                                                                                                    const res = await axios.post(`http://localhost:5000${endpoint}`, { email, password, name });
                                                                                                                                                                                          setUser(res.data.user);
                                                                                                                                                                                              } catch (err) {
                                                                                                                                                                                                    alert(err.response?.data?.error || 'Auth failed');
                                                                                                                                                                                                        }
                                                                                                                                                                                                          };

                                                                                                                                                                                                            const selectChat = (otherUser) => {
                                                                                                                                                                                                                setSelectedUser(otherUser);
                                                                                                                                                                                                                    socket.emit('chat:history', otherUser.id);
                                                                                                                                                                                                                        socket.emit('chat:read', otherUser.id);
                                                                                                                                                                                                                          };

                                                                                                                                                                                                                            const sendMessage = (e) => {
                                                                                                                                                                                                                                e.preventDefault();
                                                                                                                                                                                                                                    if (!text.trim() || !selectedUser) return;
                                                                                                                                                                                                                                        socket.emit('chat:send', { to: selectedUser.id, text });
                                                                                                                                                                                                                                            setText('');
                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                if (!user) {
                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                          <div className="login-container">
                                                                                                                                                                                                                                                                  <div className="login-card">
                                                                                                                                                                                                                                                                            <div className="avatar-logo">C</div>
                                                                                                                                                                                                                                                                                      <h2>ChatApp Login</h2>
                                                                                                                                                                                                                                                                                                <p>Login to start chatting</p>
                                                                                                                                                                                                                                                                                                          <form onSubmit={handleAuth}>
                                                                                                                                                                                                                                                                                                                      {isRegister && (
                                                                                                                                                                                                                                                                                                                                    <input type="text" placeholder="Full Name" value={name} onChange={(e) => setName(e.target.value)} required />
                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                            <input type="email" placeholder="Email" value={email} onChange={(e) => setEmail(e.target.value)} required />
                                                                                                                                                                                                                                                                                                                                                                        <input type="password" placeholder="Password" value={password} onChange={(e) => setPassword(e.target.value)} required />
                                                                                                                                                                                                                                                                                                                                                                                    <button type="submit">{isRegister ? 'Register' : 'Login'}</button>
                                                                                                                                                                                                                                                                                                                                                                                              </form>
                                                                                                                                                                                                                                                                                                                                                                                                        <span className="toggle-auth" onClick={() => setIsRegister(!isRegister)}>
                                                                                                                                                                                                                                                                                                                                                                                                                    {isRegister ? 'Already have an account? Login' : 'No account? Register'}
                                                                                                                                                                                                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="chat-app">
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className={`sidebar ${selectedUser ? 'hidden-mobile' : ''}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="sidebar-header">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="user-profile">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="avatar">{user.name[0]}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <strong>{user.name}</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <small>Logged in</small>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="online-badge">• Online: {onlineCount}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="search-bar">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input type="text" placeholder="Search user..." />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="user-list">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {users.map((u) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div key={u.id} className="user-item" onClick={() => selectChat(u)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="avatar-wrap">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="avatar">{u.name[0]}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="online-dot"></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="user-info">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <strong>{u.name}</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <small>Tap to chat</small>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {unreadMap[u.id] > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="unread-badge">{unreadMap[u.id]}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className={`chat-window ${!selectedUser ? 'hidden-mobile' : ''}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {selectedUser ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="chat-header">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button className="back-btn" onClick={() => setSelectedUser(null)}>←</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="avatar">{selectedUser.name[0]}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <strong>{selectedUser.name}</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <small>online</small>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="messages-body">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {messages.map((m, idx) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div key={idx} className={`message-bubble ${m.sender === user.id ? 'sent' : 'received'}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>{m.text}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="time">{new Date(m.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <form className="message-input" onSubmit={sendMessage}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input type="text" placeholder="Type a message" value={text} onChange={(e) => setText(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button type="submit">➤</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="empty-state">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3>WhatsApp Style Chat</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>Select a user from the left to start chatting.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="online-badge-pill">Online users: {onlineCount}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
>>>>>>> df341e11878522eef3f9a7cb60e775e263da48bc
